class MyString {
  static const KEY_TOKEN = "Token";
  static const KEY_IS_REMEMBER = "isRemember";
  static const KEY_USERNAME = "username";
  static const KEY_PASSWORD = "password";
  static const CUSTOMER_TABLE = '''CREATE TABLE IF NOT EXISTS customer (
      iDCUSTOMER INTEGER PRIMARY KEY AUTOINCREMENT,
      kODECUSTOMER TEXT,
      nAMACUSTOMER TEXT,
      aLAMAT TEXT,
      nAMAPEMILIK TEXT,
      kTPPEMILIK TEXT,
      kETERANGAN TEXT,
      kODEPOS TEXT,
      kAPASITASTOKO TEXT,
      tELPTOKO TEXT,
      tELPPEMILIK TEXT,
      iDDISTRIBUTOR INTEGER,
      nAMADISTRIBUTOR TEXT,
      iDPROVINSI INTEGER,
      nAMAPROVINSI TEXT,
      iDDISTRIK INTEGER,
      nAMADISTRIK TEXT,
      iDAREA INTEGER,
      nAMAAREA TEXT,
      iDKECAMATAN INTEGER,
      nAMAKECAMATAN TEXT,
      lATITUDE TEXT,
      lONGITUDE TEXT,
      sTATUSTOKO INTEGER,
      gROUPCUSTOMER TEXT,
      tGLLAHIR TEXT,
      bARIS TEXT,
      uSERNAME TEXT,
      kOORDINATLOCK TEXT,
      kAPASITASZAK TEXT,
      kAPASITASJUAL TEXT,
      kAPASITASTON TEXT,
      rEGION TEXT,
      nEEDSYNC INTEGER,
      iSSHOWBIRTHDAY INTEGER,
      nEEDSYNCLOCATION INTEGER,
      iSDELETE INTEGER,
      iSLOCAL INTEGER,
      iSPROGRESS INTEGER
    )''';
}
